spring:
  application:
    name: teste-api

zoro:
  log:
    enabled: true
    flush-interval-ms: 1000
    project-id: "ZL_demo_key"
    endpoint: "https://larafogos-zorolog-ingestor.2zf9jv.easypanel.host"
    tenant-id: "ZL_demo_key"
    api-key: "ZL_demo_key"
    batch-size: 50
